#rest client
GET https://localhost:7292/shoppingcart/123



#POST
POST https://localhost:7292/shoppingcart/123/items
Accept: application/json
Content-Type: application/json

[1, 2]

###

GET https://localhost:7292/events?start=0&end=20
Accept: application/json
